Jc/pdfpage
datagovsg/doculens-sg pull request #38
Opened 2022-01-25 03:18 UTC by junchernwu

## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

2022-01-25 04:25 UTC, sheikhshack requested changes
Left some comments. Thinking if possible to start looking into:
1. Storing the form submission and files into s3. Ideally this will be a multi part form? Can check with @Barry which direction hes working towards for this
2. Integrating the s3 functions into the `application` controller. Can perhaps just have a s3 service and module, and let it be imported by the `application` controller
3. Reusing some of the preexisting components. We current have a navbar available for use which follows the design master. Possible to build off that for the `Mark as complete` buttons etc

![image](https://user-images.githubusercontent.com/28633094/150910587-5acdb7cc-63d5-409d-b7ca-28734e165a09.png)


Also i think due to the lack of time, can just completely ignore mobile view for now. We just go with desktop view for simplicity

2022-01-25 04:25 UTC, sheikhshack commented on backend/src/S3/s3.controller.ts
> +import { Controller, Get, Param, Post, Req, Res } from '@nestjs/common'
Possible to integrate this with the `applications.controller`? The application controller has a post method that creates a new application (response) for each form. And we're expecting mulit file upload for that

2022-01-25 04:25 UTC, sheikhshack commented on backend/src/S3/s3.service.ts
> +config()
If we're using dotenv, is it possible to move all the local env variables and implement them in the same manner? Otherwise can just use `source .env` and store all your credentials inside

2022-01-25 04:25 UTC, sheikhshack commented on frontend/package.json
> +    "preinstall": "npx npm-force-resolutions"
curious, which package is needing this

2022-01-25 04:55 UTC, junchernwu commented on frontend/package.json
> +    "preinstall": "npx npm-force-resolutions"
its the viewer thing for the pdf! Has some issue if i dun include this preinstall script

2022-01-25 04:56 UTC, junchernwu commented on backend/src/S3/s3.service.ts
> +config()
yea I think source .env will be easier

2022-01-26 00:17 UTC, sheikhshack commented
Hey @junchernwu is this ready to be merged? Might be easier to work off what you have to prevent merge conflicts

2022-01-26 02:25 UTC, sheikhshack approved these changes

2022-01-26 02:57 UTC, merged